FROM dunglas/frankenphp:1-php8.4-bookworm

RUN install-php-extensions pdo_pgsql \
    && mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

WORKDIR /app
COPY . /app

EXPOSE 80

CMD ["frankenphp", "run", "--config", "/app/Caddyfile"]
